<a href="https://colab.research.google.com/github/anton1602/ClipsLabs/blob/master/lab1.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

# Лабораторная работа №1 по дисциплине ТГОНС

**Выполнил:**   
Студент группы М091901(76)  
Воронцов Антон


# 1.Print 'Hello HCIA'.

In [1]:
print("Hello HCIA")

Hello HCIA


# 2.Define two variables and calculate their sum.

In [2]:
a = 13
b = 37
a + b

50

# 3.Define a list and replicate in three different ways.

Для создания копии списка можно воспользоваться тремя способами:

In [3]:
old_list = [1, 2, 3]

new_list1 = old_list.copy()
new_list2 = old_list[:]
new_list3 = list(old_list)

# 4.Define two lists and merge them together.

In [4]:
list1 = [1, 2, 3]
list2 = [4, 5, 6]
list_merged = list1 + list2

list_merged

[1, 2, 3, 4, 5, 6]

# 5. Get the last element of the list and print it.

In [5]:
print(list_merged[-1])

6


# 6.Define a tuple that contains only one element.

In [6]:
tuple_1d = (1,)

print(tuple_1d, type(tuple_1d))

(1,) <class 'tuple'>


# 7.Define a three-line long string.

In [7]:
str_three_lines = "First line\nSecond line\nThird line"

print(str_three_lines)

First line
Second line
Third line


# 8.Define a tuple and then use the 'for loop' to print all the elements.

In [8]:
tuple_2 = ('meow1', 'meow2', 'ps-ps-ps')

for element in tuple_2:
    print(element)

meow1
meow2
ps-ps-ps


# 9.Define a function to do Multiplication, such as Mul(8,6),and its output 48.

In [9]:
def mul(a, b):
    return a*b

mul(8,6)

48

# 10.Import numpy and use numpy to define an array, the its shape  is (5,5) and all its elements is 0.

In [10]:
import numpy as np

zeros1 = np.zeros((5,5))

print(zeros1)
print(type(zeros1))
print(zeros1.shape)

[[0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0.]]
<class 'numpy.ndarray'>
(5, 5)


# 11.Import numpy and use numpy to define an array, the shape is (4,6) and all elements is 0.

In [11]:
zeros2 = np.zeros((4,6))

print(zeros2)
print(type(zeros2))
print(zeros2.shape)

[[0. 0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0. 0.]]
<class 'numpy.ndarray'>
(4, 6)


# 12.Use numpy.arrange() to generate an array of shape(15,), then modify the shape to(3,5).

In [12]:
vector = np.arange(15)
print(vector, vector.shape)

matrix = vector.reshape(3,5)
print(matrix, matrix.shape)

[ 0  1  2  3  4  5  6  7  8  9 10 11 12 13 14] (15,)
[[ 0  1  2  3  4]
 [ 5  6  7  8  9]
 [10 11 12 13 14]] (3, 5)


# 13.Define two matrices, then calculate and print the result of their point multiplication.

In [13]:
matrix1 = matrix.copy()
matrix2 = np.arange(15, 30).reshape(5,3)

print(matrix1)
print('*')
print(matrix2)

result = np.dot(matrix1, matrix2)

print('=')
print(result)

[[ 0  1  2  3  4]
 [ 5  6  7  8  9]
 [10 11 12 13 14]]
*
[[15 16 17]
 [18 19 20]
 [21 22 23]
 [24 25 26]
 [27 28 29]]
=
[[ 240  250  260]
 [ 765  800  835]
 [1290 1350 1410]]
